# Generated by Django 3.2.9 on 2021-11-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
